### ISSUE TITLE
dequeue method not exhaustive

### ISSUE THREAD

**Issue by bahuljain** [prakhar1989/ocaml-fun#1]
Week 3: recursive_types.ml
there's an error for the case when 'front' is an empty list and back is not empty, in which case you are supposed to return the last element of the 'back' list...

**Comment by prakhar1989** [comment]
Nice catch. However,

> in which case you are supposed to return the last element of the 'back' list...

should instead be - **return the tail of the back list**

**Comment by bahuljain** [comment]
([], back) -> (0, ([], List.tl back)) 

is still wrong.. you dont have to return 0 you have to return the tail the list back

also List.tl removes the first element of back and returns the list, you have to remove the last element of the list (or the tail of the list) and return it..try using the split method here somehow :) otherwise check my solution

**Comment by bahuljain** [comment]
https://github.com/bahuljain/Courses/blob/master/OCaml%20-%20Universit%C3%A9%20Paris%20Diderot/week%203/queue.ml

**Comment by prakhar1989** [comment]
Messed up the with zero - my bad. I would prefer using `List.rev`. Either ways, runtime characteristics of both are same, so shouldn't make a diff.
