### ISSUE TITLE
factorize method incomplete

### ISSUE THREAD

**Issue by bahuljain** [prakhar1989/ocaml-fun#2]
week 3: tree.ml
factorize method fails for the following test case:

let result : exp = factorize (EAdd (EInt 5, EAdd (EMul (EInt 3, EInt 2), EMul (EInt 3, EInt 3))));;

in which case the result should be - 

result : exp = EAdd (EInt 5, EMul (EInt 3, EAdd (EInt 2, EInt 3)))

Minor change only required :)

**Comment by bahuljain** [comment]
okay sorry its given in the remarks that recursion is not required at a deeper level. Sorry!! Never mind..Closing issue

**Comment by prakhar1989** [comment]
Hehe! No problem =)
